name: ✨ 功能请求
description: 提交新功能或改进的建议
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: 背景 & 动机
      description: 你希望解决的问题或改进点
      placeholder: 当前文档 UI 在 ... 方面体验不好，希望能够 ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 你设想的功能实现方式
  - type: textarea
    id: alternatives
    attributes:
      label: 其他可选方案
      description: 你是否考虑过其他替代方案
  - type: input
    id: related
    attributes:
      label: 相关的 Issue/PR
      description: 如果有相关 issue 或 pr，请在此附上
