/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiTest: typeof import('./../src/components/api-test.vue')['default']
    BodyParams: typeof import('./../src/components/body-params.vue')['default']
    JsonView: typeof import('./../src/components/json-view.vue')['default']
    ParamsTable: typeof import('./../src/components/params-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaView: typeof import('./../src/components/schema-view.vue')['default']
  }
}
